import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { Provider } from "react-redux";
// import { store } from "./redux/store";
import { Providers } from "./redux/Provider";
import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from "@react-oauth/google";
// import Preloader from "@/components/Preloader";
// import RouteChangeLoader from "@/components/RouteChangeLoader";
// import { Provider } from 'react-redux'
// import { store } from "./store";
import BackToTop from "@/components/BackToTop";
import RouteChangeLoader from "@/components/RouteChangeLoader";
import Navbar from "@/components/Navbar";
import VisitorFetcher from "./web-pages/VisitorFetcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Search Architect",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo/company-logo.webp", // or '/favicon.svg'
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/webp" href="/Logo/company-logo.webp" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <GoogleOAuthProvider clientId={process.env.NEXT_OAUTH_CLIENT_ID}>
          <Providers>
            <RouteChangeLoader />
            <VisitorFetcher />
            <Navbar />
            {children}
            <BackToTop />
          </Providers>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
