export const demoProperties = [
  {
    id: 1,
    title: "Modern Downtown Apartment",
    location: "Delhi",
    price: 450000,
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    image: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
    description:
      "Luxury apartment in the heart of downtown with amazing city views",
    experience: 5,
    averageRating: 4.5,
    email: "example@gmail.com",
    phone: 74747474985,
    location:"south delhi",

  },
  {
    id: 2,
    title: "Suburban Family Home",
    location: "Kerela",
    price: 750000,
    type: "House",
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    image: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
    description:
      "Spacious family home with beautiful garden and modern amenities",
    link: "/architects/${arhitect.id}",
  },
  {
    id: 3,
    title: "Luxury Penthouse",
    location: "Maharashtra",
    price: 1200000,
    type: "Penthouse",
    bedrooms: 3,
    bathrooms: 3,
    area: 2000,
    image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
    description: "Stunning penthouse with ocean views and premium finishes",
    link: "/architects/${arhitect.id}",
  },
  {
    id: 4,
    title: "Cozy Studio Loft",
    location: "Goa",
    price: 280000,
    type: "Studio",
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    image: "https://images.pexels.com/photos/2121121/pexels-photo-2121121.jpeg",
    description:
      "Industrial loft in trendy neighborhood, perfect for young professionals",
    link: "/architects/${arhitect.id}",
  },
  {
    id: 5,
    title: "Beachfront Villa",
    location: "Rajasthan",
    price: 950000,
    type: "Villa",
    bedrooms: 5,
    bathrooms: 4,
    area: 3500,
    image: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg",
    description: "Elegant villa steps away from the beach with private pool",
    link: "/architects/${arhitect.id}",
  },
  {
    id: 6,
    title: "City Center Condo",
    location: "Uttar Pradesh",
    price: 380000,
    type: "Condo",
    bedrooms: 1,
    bathrooms: 1,
    area: 800,
    image: "https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg",
    description:
      "Modern condo with access to building amenities and rooftop terrace",
    link: "/architects/${arhitect.id}",
  },
  {
    id: 7,
    title: "Mountain Retreat House",
    location: "Assam",
    price: 520000,
    type: "House",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    image: "https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg",
    description: "Peaceful house surrounded by nature with mountain views",
    link: "/architects/${arhitect.id}",
  },
  {
    id: 8,
    title: "Historic Townhouse",
    location: "Haryana",
    price: 680000,
    type: "Townhouse",
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    image: "https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg",
    description:
      "Beautifully restored townhouse with original architectural details",
    link: "/architects/${arhitect.id}",
  },
  {
    id: 9,
    title: "Luxury High-Rise Apartment",
    location: "Himachal Pradesh",
    price: 620000,
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    image: "https://images.pexels.com/photos/2121120/pexels-photo-2121120.jpeg",
    description: "High-floor apartment with panoramic city and ocean views",
    link: "/architects/${arhitect.id}",
  },
  {
    id: 10,
    title: "Garden Villa",
    location: "Delhi",
    price: 440000,
    type: "Villa",
    bedrooms: 2,
    bathrooms: 2,
    area: 1600,
    image: "https://images.pexels.com/photos/1396125/pexels-photo-1396125.jpeg",
    description:
      "Charming villa with extensive gardens and outdoor entertainment area",
    link: "/architects/${arhitect.id}",
  },
];

// export const locations = ["All Locations", "New York", "Los Angeles", "Miami", "Chicago", "Denver"];

// export const propertyTypes = ["All Types", "Apartment", "House", "Penthouse", "Studio", "Villa", "Condo", "Townhouse"];
